### ISSUE TITLE
64bit ABIv11 SystemTags() ignores NP_StackSize

### ISSUE THREAD

**Issue by alb42** [deadw00d/AROS#60]
Platform: 64bit ABIv11

When you start a program via SystemTags() with a given NP_Stacksize (e.g. 1000000) the program still has a lower stack (here 40960).

**Comment by deadw00d** [comment]
Can you paste the exact code you are using (with all tags you are passing). First review of code suggests that NP_StackSize should be utilized, so maybe it is some combination of tags that causes it to be omitted.

**Comment by alb42** [comment]
its a very trivial call just (sorry for pascal style)

SystemTags('Sys:Extras/MultiMedia/Video/Mplayer/Mplayer -gui dh1:movies/test.mpeg', [NP_StackSize, 1000000, TAG_END]);

Mplayer: http://archives.aros-exec.org/index.php?function=showfile&file=video/play/mplayer-1.0-v5.x86_64-v11-aros.zip

but then MPlayer crashes with a stack overflow message an in the linux console the stack lower and upper boundaries are printed which gets you 40960 bytes when you subtract them from each other.

When I think about, of course it could be also a bug of MPlayer, but thats not very likely isn't.
if you want, I could write a little test for it (a program calling an other which prints out the stack)

As Workaround I created a shell script which sets the stack via the cli command and starts mplayer then, which works nicely

**Comment by deadw00d** [comment]
Thanks, that's enough detail. I should be able to construct a unit test for that. I'll look into this issues in coming days. Good that you have a workaround. BTW, are you using releases from axrt.org or building your AROS from sources?

**Comment by alb42** [comment]
I used your releases. (to build my distribution) But I able to compile as well, I was just too lazy ;)

**Comment by deadw00d** [comment]
Can you do the following test: Create array of tags on stack as a variable and then use SystemTagList instead of SystemTags?

Another question that I have: Dos only exposes SystemTagList and SystemTags is a define/inline that gets compiled into an applications. How does it work for Pascal? I assume SystemTags call that you are showing is a Pascal function that calls dos.library SystemTagList?

For C, there is a translation from C varargs to an array of IPTRs happening in SystemTags define/inline. Maybe you are missing this translation in Pascal version? Note that x86_64 ABI is quite complex with regards to varargs and approaches that work on i386 and m68k, don't work on x86_64. Essentially variable length arguments are passed partially by registers and partially on stack on x86_64.

**Comment by alb42** [comment]
to be honest, we ONLY use SystemTagList, because the needed varargs in Pascal are not easily possible therefore we use a little inline function SystemTags to pass that "array of Tags" to SystemTagsList see also:
https://gitlab.com/freepascal.org/fpc/source/-/blob/main/packages/arosunits/src/amigados.pas#L2462

function SystemTags(const Command: STRPTR; const Tags: array of PtrUInt): LongInt; inline;
begin
  SystemTags := SystemTagList(Command, @Tags);
end;

array of PtrUInt -> unsigned pointer-sized integer so 64 bit on a 64 bit system (and 32 bit on a 32 bit system)
Thats our emulation of varargs, only to notice that you need to pass the variable args with [] around it, as a an array, works well for all kinds of function like OpenScreen/Window and so on and it's not too far off the original C scheme ;)

**Comment by deadw00d** [comment]
Hi, can you try this version, it should fix the issue:

https://axrt.org/development/dos.library_50.74_x86_64.zip

**Comment by alb42** [comment]
Thanks, this library fixed the problem
